<template>
  <v-content>
    <v-container
            align-start
            fluid
            class="fill-height"
    >
      <v-row
              align="start"
              justify="start"
              class="fill-height"
      >
        <v-col
                class="text-center fill-height"
                cols="12"
        >
          <g-tab-area></g-tab-area>
        </v-col>
      </v-row>
    </v-container>
  </v-content>
</template>
