<template>
  <v-content>
    <v-container
            align-start
            fluid
            class="fill-height"
    >
      <v-row
              align="start"
              justify="start"
              class="fill-height"
              v-if="top_tab_area"
      >
        <v-col
                class="text-center fill-height"
                cols="12"
        >
          <g-tab-area-top></g-tab-area-top>
        </v-col>
      </v-row>
      <v-row
              align="start"
              justify="start"
              class="fill-height"
              v-if="bottom_tab_area"
      >
        <v-col
                class="text-center fill-height"
                cols="12"
        >
          <g-tab-area-bottom></g-tab-area-bottom>
        </v-col>
      </v-row>
    </v-container>
  </v-content>
</template>
