<template>
  <v-content>
    <v-container
            fluid
            class="fill-height"
    >
      <v-row style="height: 100%"
             v-if="top_tab_area"
      >
        <v-col
                class="fill-height"
                cols="12"
        >
          <g-tab-area-top></g-tab-area-top>
        </v-col>
      </v-row>
    </v-container>
  </v-content>
</template>
