version: 2

build:
  os: ubuntu-22.04
  apt_packages:
    - graphviz
  tools:
    python: "3.11"
  jobs:
    post_checkout:
      # Use `git log` to check if the latest commit contains "skip rtd" or "rtd skip",
      # in that case exit the command with 183 to skip the build
      - MSG=`git --no-pager log --pretty="tformat:%s -- %b" -1`; case $MSG in *"skip rtd"*|*"rtd skip"*) exit 183;; *);; esac

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: true

python:
  system_packages: false
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs

# Build zipped HTML
formats:
    - htmlzip
