name: jdaviz

channels:
    - astropy

dependencies:
    - python>=3.7
    - astropy
    - Cython
    - matplotlib
    - numpy
    - sphinx-astropy
    - asteval
#   - pip:
#       - dependency_from_pip
