name: Check PR change log

on:
  pull_request:
    types: [opened, synchronize, labeled, unlabeled]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  changelog_checker:
    name: Check if change log entry is correct
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: grep -P '\[[^\]]*#${{github.event.number}}[,\]]' CHANGES.rst
        if: ${{ !contains(github.event.pull_request.labels.*.name, 'no-changelog-entry-needed') }}
