name: CI - UV Test

on:
  push:
    branches:
    - main
    - 'v*'
    tags:
    - 'v*'
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  ci_tests_uv:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.allow_failure || contains(github.event.pull_request.labels.*.name, 'continue-on-error') }}
    strategy:
      matrix:
        include:
          - name: UV - Code style checks
            os: ubuntu-latest
            python: 3.x
            test_type: codestyle
            allow_failure: false

          - name: UV - PEP 517
            os: ubuntu-latest
            python: 3.x
            test_type: pep517
            allow_failure: false

          - name: UV - Security audit
            os: ubuntu-latest
            python: 3.x
            test_type: securityaudit
            allow_failure: false

          - name: UV - Python 3.13 with coverage checking and all deps
            os: ubuntu-latest
            python: '3.13'
            test_type: py313-alldeps-cov
            pytest_posargs: --run-slow
            allow_failure: false

          - name: UV - OS X - Python 3.13
            os: macos-latest
            python: '3.13'
            test_type: py313-test
            allow_failure: false

          - name: UV - Windows - Python 3.13
            os: windows-latest
            python: '3.13'
            test_type: py313-test
            allow_failure: false

    steps:
    - name: Checkout code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
      with:
        fetch-depth: 0

    - name: Set up python ${{ matrix.python }} on ${{ matrix.os }}
      uses: actions/setup-python@cfd55ca82492758d853442341ad4d8010466803a  # v5.6.0
      with:
        python-version: ${{ matrix.python }}

    - name: Install uv
      uses: astral-sh/setup-uv@v2

    - name: Install extra dependencies for strauss
      if: "contains(matrix.test_type, 'alldeps')"
      run: |
        if [ "$RUNNER_OS" = "Linux" ]; then
          sudo apt-get install libportaudio2
        fi
      shell: bash

    - name: Run codestyle checks (flake8)
      if: "matrix.test_type == 'codestyle'"
      run: |
        echo "::group::Install flake8"
        uv pip install --system flake8
        echo "::endgroup::"
        
        echo "::group::Run flake8"
        flake8 jdaviz --count
        echo "::endgroup::"

    - name: Run PEP 517 check
      if: "matrix.test_type == 'pep517'"
      run: |
        echo "::group::Install build + twine"
        uv pip install --system build twine "importlib_metadata!=8.0.0"
        echo "::endgroup::"
        
        echo "::group::Build sdist"
        python -m build --sdist .
        echo "::endgroup::"
        
        echo "::group::Check dist"
        twine check dist/* --strict
        echo "::endgroup::"

    - name: Run security audit
      if: "matrix.test_type == 'securityaudit'"
      run: |
        echo "::group::Install bandit"
        uv pip install --system bandit
        echo "::endgroup::"
        
        echo "::group::Run bandit"
        bandit -r jdaviz -c .bandit.yaml
        echo "::endgroup::"

    - name: Install jdaviz with test dependencies
      if: "contains(matrix.test_type, 'test') || contains(matrix.test_type, 'cov')"
      shell: bash
      run: |
        echo "::group::Dependency resolution and installation"
        uv pip install --system -e ".[test]"
        if [[ "${{ matrix.test_type }}" == *"alldeps"* ]]; then
          uv pip install --system -e ".[all]"
        fi
        echo "::endgroup::"

    - name: Display installed packages
      if: "contains(matrix.test_type, 'test') || contains(matrix.test_type, 'cov')"
      run: |
        echo "::group::Installed packages"
        uv pip list --system
        echo "::endgroup::"

    - name: Run pytest
      if: "contains(matrix.test_type, 'test') || contains(matrix.test_type, 'cov')"
      shell: bash
      env:
        MPLBACKEND: agg
        JUPYTER_PLATFORM_DIRS: "1"
      run: |
        echo "::group::Run tests"
        if [[ "${{ matrix.test_type }}" == *"cov"* ]]; then
          python -m pytest -n auto --dist loadfile --pyargs jdaviz docs --cov jdaviz --cov-config=pyproject.toml --ignore=jdaviz/qt.py --durations=30 --memlog ${{ matrix.pytest_posargs }}
          coverage xml
        else
          python -m pytest -n auto --dist loadfile --pyargs jdaviz docs --ignore=jdaviz/qt.py --durations=30 --memlog ${{ matrix.pytest_posargs }}
        fi
        echo "::endgroup::"

    - name: Upload coverage to artifacts
      if: "contains(matrix.test_type, 'cov')"
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a  # v7.0.1
      with:
        name: coverage_uv_${{ matrix.test_type }}.xml
        path: coverage.xml
        if-no-files-found: error
